### ISSUE TITLE
Serialization for Immutable objects other than List/Map

### ISSUE THREAD

**Issue by qimingweng** [glenjamin/transit-immutable-js#1]
Since Immutable already does .toJSON and .fromJS, and those functions support List/Map, I'm looking for a serialization library that can do more than just those. Maybe not Records, because I'm not sure how functions would be serializable, but Sets, and OrderedMaps come to mind as being really important.

**Comment by glenjamin** [comment]
The main advantage currently provided is the preservation of complex map keys - as this was the particular problem I had at the time of writing.

I think it is pretty easy to support the other built-in data types using similar code to List and Map - I'd take a PR for this. I'll try and add it myself if I have time and no-one else has done so.

Records would also be fairly straightforward, but the user would need to provide a lookup function to locate the constructor of given a record name

**Comment by glenjamin** [comment]
Support for Sets and OrderedMaps has been added in b323bc5bf90eabd71644d64cd2e4655409baa9e6 and published as `v0.2.0`

**Comment by qimingweng** [comment]
@glenjamin That's awesome, thanks for adding it :+1:

**Comment by corbt** [comment]
Support for Records as well as all other types mentioned here is available as of 0.5.0, so I'm closing this. If there are other ImmutableJS types that users want feel free to open another issue.
