### ISSUE TITLE
More graceful way of dealing with non-existing record-types

### ISSUE THREAD

**Issue by freakinruben** [glenjamin/transit-immutable-js#18]
I use transit-immutable-js for (de-)serialising the state of my app to local-storage. I regularly run into the issue of having an error thrown when a record-type doesn't exist, for example when I switch feature-branches that change the data-model.

Being able to solve those missing records manually would be very nice, for example being able to decide to skip deserialising a missing record or change it to a different record-type, without the whole deserialising process failing. This would make making changes to the data-model to an already deployed app a lot easier..

Is this a feature you're open for? I could write an implementation if so.

**Comment by glenjamin** [comment]
Yep, that sounds reasonable to me

**Comment by glenjamin** [comment]
Resolved by #19 - released in `v0.6.0`
