### ISSUE TITLE
Question about array initializer

### ISSUE THREAD

**Issue by qimingweng** [glenjamin/transit-immutable-js#2]
I'm curious what's happening here https://github.com/glenjamin/transit-immutable-js/blob/master/index.js#L48

The line is:

```
var i = 0, a = new Array(m.size);
```

If I'm not mistaken, isn't the final array size after the loop `2 * m.size`? I'm curious why the array is initialized with half the size to begin with. (Or if there are any performance benefits to having the array initialized with a size a tall, instead of `a = []`).

**Comment by glenjamin** [comment]
Good spot! That should be `2 *`, I've pushed a commit to fix that.

At some point when I last looked into this, there was some performance benefit to indicating the size of the array. Some quick tests at http://jsperf.com/allocating-array-size/11 seem to indicate this is still the case (although I can't see to get the graphs to load right now).

Intuitively, I'm giving the JS engine information it would be tricky to infer, so it seems like it should be helpful.
