### ISSUE TITLE
`\s` is not encoded properly, breaks further fromJSON()

### ISSUE THREAD

**Issue by nkbt** [glenjamin/transit-immutable-js#20]
![20160608-133553](https://cloud.githubusercontent.com/assets/175264/15882299/a672cb8a-2d80-11e6-9bba-772da9749618.png)

![20160608-133702](https://cloud.githubusercontent.com/assets/175264/15882300/a67880fc-2d80-11e6-8526-fa261f42a4cd.png)

It could be purely `transit-js` issue, will move to upstream if not the problem of `transit-immutable-js`

My JSON after encoding looks like this:

```json
[
  "^ ",
  "componentRouter",
  [
    "^ ",
    "pathname",
    "/ddos",
    "hash",
    null,
    "query",
    [
      "^ ",
      "filters",
      "blabla\sqwer"
    ],
    "cleanQuery",
    [
      "^ ",
      "^4",
      "blabla\sqwer"
    ],
    "defaultParams",
    [
      "^ "
    ],
    "routes",
    [
      "^ ",
      "/ddos",
      [
        "^ ",
        "route",
        "/ddos",
        "regex",
        "~^/ddos$",
        "params",
        [
          "^ "
        ]
      ]
    ],
    "currentRoute",
    [
      "^ ",
      "^9",
      "/ddos",
      "^:",
      "~^/ddos$",
      "^;",
      [
        "^ "
      ]
    ],
    "locationType",
    "LOCATION_HISTORY"
  ]
]
```

Some context: this is universal JS app, I serialize Redux store on a server (partially immutable-js, partially plain objects) and then I am trying to deserialize it in a browser. Accidentally my route had `something\something` in it, and that `\s` broke `fromJSON()` because backslash was not escaped.

## Expected value:

```json
[
  "^ ",
  "componentRouter",
  "...cut",
  [
    "query",
    [
      "^ ",
      "filters",
      "blabla\\sqwer"
    ],
    "cleanQuery",
    [
      "^ ",
      "^4",
      "blabla\\sqwer"
    ]
  ],
  "...cut"
]
```

**Comment by nkbt** [comment]
`\b` is ok for some reason. But other combinations like `\a`, `\c` fail too.

**Comment by glenjamin** [comment]
This is almost certainly a problem with upstream - there's nothing in this module that should affect string escaping

**Comment by nkbt** [comment]
Thanks. Will move it there then

**Comment by nkbt** [comment]
Closing for now, will reopen if not upstream issue.
