### ISSUE TITLE
add warning about potential exposure to XSS attacks?

### ISSUE THREAD

**Issue by busticated** [glenjamin/transit-immutable-js#23]
hey there -

very helpful library - thanks for putting it together. i realize this could be seen as out of scope ([ref](https://github.com/cognitect/transit-js/issues/31)) but figured i'd suggest it anyway.

if you naively embed the raw JSON provided via `transit.toJSON` into your html page, you expose yourself to XSS attacks. 

simple example:

    // somewhere on your server
    var data = transit.toJSON({ xss: '</script><script>alert(\'evil\');</script><script>' });

    // somewhere in your html / view rendering 
    <script id="my-data" type="application/json">${data}</script>

might want to just throw a little disclaimer into the docs - i can take a crack at it if you agree :)

-matt

**Comment by glenjamin** [comment]
Does the same thing happen when using JSON.stringify?

A note in the docs sounds good, PR welcome.

**Comment by busticated** [comment]
> Does the same thing happen when using JSON.stringify?

yep, it's a fairly well-known gotcha :-/

> A note in the docs sounds good, PR welcome.

done --> https://github.com/glenjamin/transit-immutable-js/pull/24

thanks again for the lib!

**Comment by glenjamin** [comment]
Nice one, thanks!
