### ISSUE TITLE
Module not found: Error: Can't resolve 'transit-js' in 'transit-immutable-js'

### ISSUE THREAD

**Issue by alexicum** [glenjamin/transit-immutable-js#34]
Installing transit-immutable-js not installing transit-js

```
ERROR in ./~/transit-immutable-js/index.js
Module not found: Error: Can't resolve 'transit-js' in '[project-root]\node_modules\transit-immutable-js'
 @ ./~/transit-immutable-js/index.js 1:14-35
 @ ./app/store/localStorage.js
 @ ./app/app.js
```

**Comment by glenjamin** [comment]
https://github.com/glenjamin/transit-immutable-js/blob/master/package.json#L21-L24

I imagine there's a `peerDependency` warning from npm you're ignoring somewhere?

**Comment by alexicum** [comment]
Yes:
```
warning "transit-immutable-js@0.7.0" has unmet peer dependency "transit-js@>= 0.8".
warning "babel-plugin-rewire@1.0.0" has unmet peer dependency "babel-template@^6.2.0".
warning "babel-plugin-rewire@1.0.0" has unmet peer dependency "babel-types@^6.2.0".
```

Do I need install them manually?

**Comment by glenjamin** [comment]
Yep, since npm 3 peer dependencies have to be manually selected and installed.

**Comment by smmoosavi** [comment]
I think we should change `npm install transit-immutable-js` to `npm install transit-js transit-immutable-js` to readme.
