### ISSUE TITLE
Lists are being restored as Maps

### ISSUE THREAD

**Issue by brunolemos** [glenjamin/transit-immutable-js#36]
I'm not sure this is an issue with this package or with https://github.com/rt2zz/redux-persist-immutable (that uses this package), so I'm posting on both. cc @rt2zz

I use redux, and `List` or `Set` is being rehydrated as objects.

## Reproduction (reducer example)
```js
return Map({
  test1: List(['a', 'b', Math.random()]),
  test2: Set(['a', 'b', Math.random()]),
})
```

## Before rehydration
![image](https://cloud.githubusercontent.com/assets/619186/26533227/7dc3ffdc-43ec-11e7-8623-bbe3573de15a.png)

## After rehydration

![image](https://cloud.githubusercontent.com/assets/619186/26533229/8ba6aa00-43ec-11e7-9fa7-77a1ab2a1b8a.png)

**Comment by nkbt** [comment]
Must be a duplicate of https://github.com/glenjamin/transit-immutable-js/issues/32

See comments for solutions

**Comment by brunolemos** [comment]
Thanks @nkbt it was indeed a duplicate!
Posted my fix here, to the ones using react-native: https://github.com/facebook/react-native/issues/13746#issuecomment-304568558
