### ISSUE TITLE
ignoring or blacklisting certain keys

### ISSUE THREAD

**Issue by salzhrani** [glenjamin/transit-immutable-js#4]
I currently need this feature to skip serialization of certain keys... if you think it is useful I can submit a PR with the implementation.

**Comment by glenjamin** [comment]
At the top level, or deep? If it's just the top level, I'd advise to just filter before passing to transit.

If deep, I could live with a single predicate as the second argument which would be checked against every key-value pair, and return a boolean to indicate if the key should be included. Similar to the `replacer` argument in `JSON.stringify`.

**Comment by glenjamin** [comment]
Fixed by #5
