### ISSUE TITLE
having to use the .get('propertyname') accesor instead of simply ".propertyname"

### ISSUE THREAD

**Issue by livemixlove** [glenjamin/transit-immutable-js#41]
When I access a value of a Map like so:

`MyImmutableMap.AnotherImmutableMap`

AnotherImmutableMap is undefined

But if I access it like so:
`MyImmutableMap.get('AnotherImmutableMap')`
then it returns as normal.

Is this a bug?

**Comment by livemixlove** [comment]
To clarify, this is after I've converted a transit.toJSON() string back to immutable with transit.fromJSON()

**Comment by glenjamin** [comment]
Direct property access should never work on Maps, even before going through transit.

Can you show a sample where it works before conversion but not after?

**Comment by livemixlove** [comment]
Is that not part of the immutable-js spec?  Mindblown.

Somehow this has not been an issue for me.  Investigating...

**Comment by livemixlove** [comment]
Ah, sorry, not Maps.  I'm using Records.  I didn't know they had different accessor functions.

I found this: https://github.com/glenjamin/transit-immutable-js#transitwithrecordsarray-recordclasses-missingrecordhandler--null--transit

I believe that resolves my confusion.
