### ISSUE TITLE
Performance of transit.toJSON - vs - JSON.stringify?

### ISSUE THREAD

**Issue by Slapbox** [glenjamin/transit-immutable-js#51]
Perhaps this is a nonsensical question, but I saw this library recommended by a member of the `immutable-js` team for performance over `JSON.stringify(m.toJS())`.

Is `transit.toJSON(m)` any different in terms of performance?

Thanks!

**Comment by glenjamin** [comment]
It's not something i've benchmarked, and if this is important to you I suggest you do some of your own benchmarking to confirm.

It is possible for transit to be faster for two reasons:
- it doesn't require an intermediary conversion to plain JS types
- it is able to improve compression by referencing repeated items in the data

**Comment by Slapbox** [comment]
@glenjamin thanks very much for letting me know it's not an outright absurd idea. If I get a chance to do some testing I'll share it here.
