### ISSUE TITLE
here v0.7.0 but 0.8.0 on npmjs

### ISSUE THREAD

**Issue by Skywalker13** [glenjamin/transit-immutable-js#56]
It seems that this repository is outdated because the version of this module is 0.8.0 on npmjs:
![image](https://user-images.githubusercontent.com/397862/100859480-8e760900-348f-11eb-8f44-27371f7f6d94.png)

and it's still 0.7.0 here

**Comment by glenjamin** [comment]
Oh whoops! Good spot.

For reference, there was no meaningful diff:

```diff
> git diff v0.8.0 ef892b2fff2b3be6541dfb0f883a318f9b412af8
diff --git a/package.json b/package.json
index 87feebe..c23712d 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "name": "transit-immutable-js",
-  "version": "0.8.0",
+  "version": "0.7.0",
   "description": "Transit serialisation for Immutable.js",
   "main": "index.js",
   "scripts": {
```
